#!/usr/bin/env bash
#
# wander-pair.sh — Wander's own pairing-file helper.
#
# Generates a valid iOS 17+/26 pairing file for the connected iPhone (with the
# UDID field the idevice tunnel requires) and places it into the Wander app's
# container so location simulation works. No iloader/manual pymobiledevice3 needed.
#
# Usage:
#   ./tools/wander-pair.sh              # pair the connected device into Wander
#   ./tools/wander-pair.sh --sidestore  # also refresh SideStore's pairing
#
set -euo pipefail

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo "wander-pair — set up Wander's pairing file so location simulation works."
  echo "Usage: ./wander-pair.sh [--sidestore]"
  echo "  --sidestore   also refresh SideStore's own pairing"
  echo "Requires: iPhone connected via USB + unlocked + trusted, and Wander installed."
  exit 0
fi

VENV="${WANDER_VENV:-$HOME/.wander-pair-venv}"
WANDER_BUNDLE_HINT="stik"          # our fork's bundle id contains this
PAIR_TMP="$(mktemp -t wander-pair).plist"

log() { printf "\033[1;34m[wander-pair]\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m[error]\033[0m %s\n" "$*" >&2; }

# 1. Ensure pymobiledevice3 is available in a private venv.
if [ ! -x "$VENV/bin/pymobiledevice3" ]; then
  log "Setting up pairing tools (one time)…"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet pymobiledevice3
fi
PMD="$VENV/bin/pymobiledevice3"

# 2. Find the connected device UDID.
log "Looking for a connected iPhone…"
UDID="$("$PMD" usbmux list 2>/dev/null | python3 -c "
import sys, json
try: d = json.load(sys.stdin)
except Exception: d = []
usb = [x for x in d if x.get('ConnectionType')=='USB'] or d
print(usb[0]['UniqueDeviceID'] if usb else '')
")"
if [ -z "$UDID" ]; then
  err "No device found. Plug your iPhone in via USB, unlock it, and tap Trust."
  exit 1
fi
log "Device: $UDID"

# 3. Get a working idevice-format pairing file.
#    Prefer SideStore's existing ALTPairingFile — it's generated by iloader/idevice,
#    which is the exact format Wander's tunnel accepts. pymobiledevice3's own
#    save-pair-record produces a cert format the idevice tunnel rejects ("no valid
#    public key bytes"), so we only fall back to it when SideStore isn't present.
SS_SRC="$("$PMD" apps list 2>/dev/null | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k in d:
    if 'sidestore' in k.lower(): print(k); break
")"
if [ -n "$SS_SRC" ] && "$PMD" apps pull "$SS_SRC" "Documents/ALTPairingFile.mobiledevicepairing" "$PAIR_TMP" >/dev/null 2>&1 && [ -s "$PAIR_TMP" ]; then
  log "Using SideStore's pairing (idevice-format, known good)."
else
  log "No SideStore pairing found — generating one (if the tunnel rejects it, place it via iloader instead)…"
  "$PMD" lockdown save-pair-record "$PAIR_TMP" >/dev/null
  grep -qa "<key>UDID</key>" "$PAIR_TMP" || plutil -insert UDID -string "$UDID" "$PAIR_TMP"
fi
plutil -lint "$PAIR_TMP" >/dev/null || { err "Pairing file is invalid."; exit 1; }
log "Pairing file ready ($(wc -c <"$PAIR_TMP" | tr -d ' ') bytes)."

# 4. Find the installed Wander bundle id.
place_into() {   # $1 = bundle id, $2 = friendly name
  local bundle="$1" name="$2"
  # Fresh installs have no Pairing dir yet — create it, ignoring shell noise.
  printf 'mkdir "Library/Application Support/Pairing"\n' | "$PMD" apps afc "$bundle" >/dev/null 2>&1 || true
  "$PMD" apps push "$bundle" "$PAIR_TMP" "Documents/rp_pairing_file.plist" >/dev/null 2>&1 || true
  "$PMD" apps push "$bundle" "$PAIR_TMP" "Library/Application Support/Pairing/rp_pairing_file.plist" >/dev/null 2>&1 || true
  local check; check="$(mktemp)"
  if "$PMD" apps pull "$bundle" "Library/Application Support/Pairing/rp_pairing_file.plist" "$check" >/dev/null 2>&1 && [ -s "$check" ]; then
    log "✓ Verified pairing in $name ($(wc -c <"$check" | tr -d ' ') bytes)."
  else
    log "Placed into $name (migrates from Documents on first launch)."
  fi
  rm -f "$check"
}

WANDER="$("$PMD" apps list 2>/dev/null | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k,v in d.items():
    if '$WANDER_BUNDLE_HINT' in k.lower() or (v.get('CFBundleDisplayName','')=='Wander'):
        print(k); break
")"
if [ -z "$WANDER" ]; then
  err "Wander isn't installed. Sideload it first, then re-run this."
  exit 1
fi
place_into "$WANDER" "Wander"

# 5. Optionally refresh SideStore's pairing too.
if [ "${1:-}" = "--sidestore" ]; then
  SS="$("$PMD" apps list 2>/dev/null | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k in d:
    if 'sidestore' in k.lower(): print(k); break
")"
  [ -n "$SS" ] && "$PMD" apps push "$SS" "$PAIR_TMP" "Documents/ALTPairingFile.mobiledevicepairing" >/dev/null 2>&1 && log "Refreshed SideStore pairing."
fi

rm -f "$PAIR_TMP"
log "Done. Open Wander (with LocalDevVPN connected) and simulate."
