// GENERATED by SimStubs/generate_stubs.py -- do not edit by hand.
//
// Simulator-only stand-in for the device-only Rust static library
// Wander/idevice/libidevice_ffi.a (arm64 iOS slice only). Linked ONLY when
// building with -sdk iphonesimulator, via LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*].
// Never part of a device build.
//
// Every entry point fails honestly instead of pretending to succeed:
//  * out-parameters are zeroed before returning, so callers never read garbage;
//  * IdeviceFfiError-returning functions return a non-NULL, statically
//    allocated error, which idevice_error_free() below deliberately ignores.

#include "idevice.h"
#include <stddef.h>
#include <string.h>

#if !TARGET_OS_SIMULATOR
#error "idevice_ffi_sim_stubs.c must never be compiled into a device build."
#endif

static const char kWanderSimStubMessage[] =
    "Simulator build: the idevice tunnel library is stubbed out. "
    "Device connection, tunnelling and location spoofing are unavailable here.";

// Statically allocated so idevice_error_free() can safely be a no-op.
static struct IdeviceFfiError kWanderSimStubError = {
    -9001, 0, kWanderSimStubMessage
};

static struct IdeviceFfiError *wander_sim_stub_error(void) {
    return &kWanderSimStubError;
}

void adapter_free(struct AdapterHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *afc_client_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct AfcClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

void afc_client_free(struct AfcClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *afc_file_close(struct AfcFileHandle *handle) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *afc_file_open(struct AfcClientHandle *client, const char *path, enum AfcFopenMode mode, struct AfcFileHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *afc_file_write(struct AfcFileHandle *handle, const uint8_t *data, size_t length) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *afc_make_directory(struct AfcClientHandle *client, const char *path) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *app_service_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct AppServiceHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

void app_service_free(struct AppServiceHandle *handle) {
    (void)handle;
}

void app_service_free_process_list(struct ProcessTokenC *processes, uintptr_t count) {
    (void)processes;
    (void)count;
}

void app_service_free_signal_response(struct SignalResponseC *response) {
    (void)response;
}

struct IdeviceFfiError *app_service_list_processes(struct AppServiceHandle *handle, struct ProcessTokenC **processes, uintptr_t *count) {
    if (processes) *processes = NULL;
    if (count) *count = 0;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *app_service_send_signal(struct AppServiceHandle *handle, uint32_t pid, uint32_t signal, struct SignalResponseC **response) {
    if (response) *response = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *debug_proxy_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct DebugProxyHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

void debug_proxy_free(struct DebugProxyHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *debug_proxy_read_response(struct DebugProxyHandle *handle, char **response) {
    if (response) *response = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *debug_proxy_send_ack(struct DebugProxyHandle *handle) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *debug_proxy_send_command(struct DebugProxyHandle *handle, struct DebugserverCommandHandle *command, char **response) {
    if (response) *response = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *debug_proxy_send_raw(struct DebugProxyHandle *handle, const uint8_t *data, uintptr_t len) {
    return wander_sim_stub_error();
}

void debug_proxy_set_ack_mode(struct DebugProxyHandle *handle, int enabled) {
    (void)handle;
    (void)enabled;
}

void debugserver_command_free(struct DebugserverCommandHandle *command) {
    (void)command;
}

struct DebugserverCommandHandle *debugserver_command_new(const char *name, const char *const *argv, uintptr_t argv_count) {
    return NULL;
}

void heartbeat_client_free(struct HeartbeatClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *heartbeat_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct HeartbeatClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *heartbeat_get_marco(struct HeartbeatClientHandle *client, uint64_t interval, uint64_t *new_interval) {
    if (new_interval) *new_interval = 0;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *heartbeat_send_polo(struct HeartbeatClientHandle *client) {
    return wander_sim_stub_error();
}

void idevice_data_free(uint8_t *data, uintptr_t len) {
    (void)data;
    (void)len;
}

void idevice_error_free(struct IdeviceFfiError *err) {
    (void)err;
}

enum IdeviceLoggerError idevice_init_logger(enum IdeviceLogLevel console_level, enum IdeviceLogLevel file_level, char *file_path) {
    return Success;
}

void idevice_pairing_file_free(struct IdevicePairingFile *pairing_file) {
    (void)pairing_file;
}

struct IdeviceFfiError *idevice_pairing_file_read(const char *path, struct IdevicePairingFile **pairing_file) {
    if (pairing_file) *pairing_file = NULL;
    return wander_sim_stub_error();
}

void idevice_provider_free(struct IdeviceProviderHandle *provider) {
    (void)provider;
}

void idevice_string_free(char *string) {
    (void)string;
}

struct IdeviceFfiError *idevice_tcp_provider_new(const idevice_sockaddr *ip, struct IdevicePairingFile *pairing_file, const char *label, struct IdeviceProviderHandle **provider) {
    if (provider) *provider = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *image_mounter_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct ImageMounterHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *image_mounter_copy_devices(struct ImageMounterHandle *client, plist_t **devices, size_t *devices_len) {
    if (devices) *devices = NULL;
    if (devices_len) *devices_len = 0;
    return wander_sim_stub_error();
}

void image_mounter_free(struct ImageMounterHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *image_mounter_mount_personalized_with_callback_rsd(struct ImageMounterHandle *client, struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, const uint8_t *image, size_t image_len, const uint8_t *trust_cache, size_t trust_cache_len, const uint8_t *build_manifest, size_t build_manifest_len, const void *info_plist, uint64_t unique_chip_id, void (*callback)(size_t progress, size_t total, void *context), void *context) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *image_mounter_query_developer_mode_status(struct ImageMounterHandle *client, int *status) {
    if (status) *status = 0;
    return wander_sim_stub_error();
}

void installation_proxy_client_free(struct InstallationProxyClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *installation_proxy_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct InstallationProxyClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *installation_proxy_get_apps(struct InstallationProxyClientHandle *client, const char *application_type, const char *const *bundle_identifiers, size_t bundle_identifiers_len, void **out_result, size_t *out_result_len) {
    if (out_result) *out_result = NULL;
    if (out_result_len) *out_result_len = 0;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *installation_proxy_upgrade(struct InstallationProxyClientHandle *client, const char *package_path, plist_t options) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *location_simulation_clear(struct LocationSimulationHandle *handle) {
    return wander_sim_stub_error();
}

void location_simulation_free(struct LocationSimulationHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *location_simulation_new(struct RemoteServerHandle *server, struct LocationSimulationHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *location_simulation_set(struct LocationSimulationHandle *handle, double latitude, double longitude) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *lockdown_location_simulation_clear(struct LocationSimulationServiceHandle *handle) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *lockdown_location_simulation_connect(struct IdeviceProviderHandle *provider, struct LocationSimulationServiceHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

void lockdown_location_simulation_free(struct LocationSimulationServiceHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *lockdown_location_simulation_set(struct LocationSimulationServiceHandle *handle, const char *latitude, const char *longitude) {
    return wander_sim_stub_error();
}

void lockdownd_client_free(struct LockdowndClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *lockdownd_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct LockdowndClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *lockdownd_get_value(struct LockdowndClientHandle *client, const char *key, const char *domain, plist_t *out_plist) {
    if (out_plist) *out_plist = NULL;
    return wander_sim_stub_error();
}

void misagent_client_free(struct MisagentClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *misagent_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct MisagentClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *misagent_copy_all(struct MisagentClientHandle *client, uint8_t ***out_profiles, size_t **out_profiles_len, size_t *out_count) {
    if (out_profiles) *out_profiles = NULL;
    if (out_profiles_len) *out_profiles_len = NULL;
    if (out_count) *out_count = 0;
    return wander_sim_stub_error();
}

void misagent_free_profiles(uint8_t **profiles, size_t *lens, size_t count) {
    (void)profiles;
    (void)lens;
    (void)count;
}

struct IdeviceFfiError *misagent_install(struct MisagentClientHandle *client, const uint8_t *profile_data, size_t profile_len) {
    return wander_sim_stub_error();
}

struct IdeviceFfiError *misagent_remove(struct MisagentClientHandle *client, const char *profile_id) {
    return wander_sim_stub_error();
}

void plist_dict_set_item(plist_t node, const char* key, plist_t item) {
    (void)node;
    (void)key;
    (void)item;
}

void plist_free(plist_t plist) {
    (void)plist;
}

void plist_get_string_val(plist_t node, char **val) {
    if (val) *val = NULL;
}

void plist_get_uint_val(plist_t node, uint64_t * val) {
    if (val) *val = 0;
}

void plist_mem_free(void* ptr) {
    (void)ptr;
}

plist_t plist_new_dict(void) {
    return NULL;
}

plist_t plist_new_string(const char *val) {
    return NULL;
}

plist_err_t plist_to_bin(plist_t plist, char **plist_bin, uint32_t * length) {
    if (plist_bin) *plist_bin = NULL;
    if (length) *length = 0;
    return PLIST_ERR_UNKNOWN;
}

plist_err_t plist_to_xml(plist_t plist, char **plist_xml, uint32_t * length) {
    if (plist_xml) *plist_xml = NULL;
    if (length) *length = 0;
    return PLIST_ERR_UNKNOWN;
}

void process_control_free(struct ProcessControlHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *process_control_launch_app(struct ProcessControlHandle *handle, const char *bundle_id, const char *const *env_vars, uintptr_t env_vars_count, const char *const *arguments, uintptr_t arguments_count, bool start_suspended, bool kill_existing, uint64_t *pid) {
    if (pid) *pid = 0;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *process_control_new(struct RemoteServerHandle *server, struct ProcessControlHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *remote_server_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct RemoteServerHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

void remote_server_free(struct RemoteServerHandle *handle) {
    (void)handle;
}

void rp_pairing_file_free(struct RpPairingFileHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *rp_pairing_file_read(const char *path, struct RpPairingFileHandle **out) {
    if (out) *out = NULL;
    return wander_sim_stub_error();
}

void rsd_free_services(struct CRsdServiceArray *services) {
    (void)services;
}

struct IdeviceFfiError *rsd_get_services(struct RsdHandshakeHandle *handle, struct CRsdServiceArray **services) {
    if (services) *services = NULL;
    return wander_sim_stub_error();
}

void rsd_handshake_free(struct RsdHandshakeHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *rsd_service_available(struct RsdHandshakeHandle *handle, const char *service_name, bool *available) {
    if (available) *available = 0;
    return wander_sim_stub_error();
}

void screenshot_client_free(struct ScreenshotClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *screenshot_client_new(struct RemoteServerHandle *server, struct ScreenshotClientHandle **handle) {
    if (handle) *handle = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *screenshot_client_take_screenshot(struct ScreenshotClientHandle *handle, uint8_t **data, uintptr_t *len) {
    if (data) *data = NULL;
    if (len) *len = 0;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *springboard_services_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct SpringBoardServicesClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

void springboard_services_free(struct SpringBoardServicesClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *springboard_services_get_icon(struct SpringBoardServicesClientHandle *client, const char *bundle_identifier, void **out_result, size_t *out_result_len) {
    if (out_result) *out_result = NULL;
    if (out_result_len) *out_result_len = 0;
    return wander_sim_stub_error();
}

void syslog_relay_client_free(struct SyslogRelayClientHandle *handle) {
    (void)handle;
}

struct IdeviceFfiError *syslog_relay_connect_rsd(struct AdapterHandle *provider, struct RsdHandshakeHandle *handshake, struct SyslogRelayClientHandle **client) {
    if (client) *client = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *syslog_relay_next(struct SyslogRelayClientHandle *client, char **log_message) {
    if (log_message) *log_message = NULL;
    return wander_sim_stub_error();
}

struct IdeviceFfiError *tunnel_create_rppairing(const idevice_sockaddr *addr, idevice_socklen_t addr_len, const char *hostname, struct RpPairingFileHandle *pairing_file, const char *(*pin_callback)(void *context), void *pin_context, struct AdapterHandle **out_adapter, struct RsdHandshakeHandle **out_handshake) {
    if (out_adapter) *out_adapter = NULL;
    if (out_handshake) *out_handshake = NULL;
    return wander_sim_stub_error();
}
